[server]
maxMessageSize = 1000

[[theme.fontFaces]]
family = "Quicksand"
url = "https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap"

[[theme.fontFaces]]
family = "Lekton"
url = "https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&display=swap"

[[theme.fontFaces]]
family = "Source Code Pro"
url = "https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap"

[theme]
base = "dark"
baseFontSize = 15
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showWidgetBorder = false
baseRadius = "0.3rem"
font = "Source Code Pro"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"